#!/usr/bin/env bun
// Pre-build step: read each PNG in src/public/logos and emit src/web/logos-embedded.ts
// with base64 constants. Keeps logos working in the single-file bun-linked binary.

import { readdirSync } from "node:fs";
import { join } from "node:path";

const LOGO_DIR = join(import.meta.dir, "..", "src", "public", "logos");
const OUT_FILE = join(import.meta.dir, "..", "src", "web", "logos-embedded.ts");

const files = readdirSync(LOGO_DIR).filter(f => f.endsWith(".png")).sort();

const entries: string[] = [];
for (const f of files) {
  const bytes = await Bun.file(join(LOGO_DIR, f)).arrayBuffer();
  const b64 = Buffer.from(bytes).toString("base64");
  entries.push(`  ${JSON.stringify(f)}: ${JSON.stringify(b64)},`);
}

const content = `// AUTO-GENERATED by scripts/embed-logos.ts — do not edit by hand.
// Source: src/public/logos/*.png

export const LOGO_B64: Record<string, string> = {
${entries.join("\n")}
};
`;

await Bun.write(OUT_FILE, content);
console.log(`✓ Embedded ${files.length} logos (${(content.length / 1024).toFixed(0)} KB) → ${OUT_FILE}`);
